In [14]:
import pandas as pd

# Carregar os dados do arquivo CSV
df = pd.read_csv('dataset_telco_kaggle.csv')

# Exibir as primeiras linhas do DataFrame
df.head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [15]:
from pycaret.classification import *

# Initialize the PyCaret environment
clf = setup(data=df, target='Churn', session_id=123)

# Compare models to find the best one
best_model = compare_models()

# Finalize the model
final_model = finalize_model(best_model)

# Print the best model
print(final_model)

/opt/homebrew/anaconda3/envs/churnenv/lib/python3.10/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py:323: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  master_display_.apply(

Pipeline(memory=Memory(location=None),
         steps=[('label_encoding',
                 TransformerWrapperWithInverse(exclude=None, include=None,
                                               transformer=LabelEncoder())),
                ('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['SeniorCitizen', 'tenure',
                                             'MonthlyCharges'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False...
                                    transformer=TargetEncoder(cols=['customerID',
                                                                    'TotalCharges'],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              hierarchy=None,
                                                              min_samples_leaf=20,
                                                              return_df=True,
                                                              smoothing=10,
                                                              verbose=0))),
                ('actual_estimator',
                 KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                      metric='minkowski', metric_params=None,
                                      n_jobs=-1, n_neighbors=5, p=2,
                                      weights='uniform'))],
         verbose=False)

In [16]:
save_model(final_model, 'churn_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['SeniorCitizen', 'tenure',
                                              'MonthlyCharges'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False...
                                     transformer=TargetEncoder(cols=['customerID',
                                                                     'TotalCharges'],
                                                               drop_invariant=False,
                                                               handle_missing='return_nan',
                                                               handle_unknown='value',
                                                               hierarchy=None,
                                                               min_samples_leaf=20,
                                                               return_df=True,
                                                               smoothing=10,
                                                               verbose=0))),
                 ('actual_estimator',
                  KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                       metric='minkowski', metric_params=None,
                                       n_jobs=-1, n_neighbors=5, p=2,
                                       weights='uniform'))],
          verbose=False),
 'churn_model.pkl')

In [22]:
from pydantic import BaseModel
from typing import Optional

class TelcoCustomerInput(BaseModel):
    customerID: str
    gender: str
    SeniorCitizen: int
    Partner: str
    Dependents: str
    tenure: int
    PhoneService: str
    MultipleLines: str
    InternetService: str
    OnlineSecurity: str
    OnlineBackup: str
    DeviceProtection: str
    TechSupport: str
    StreamingTV: str
    StreamingMovies: str
    Contract: str
    PaperlessBilling: str
    PaymentMethod: str
    MonthlyCharges: float
    TotalCharges: str
    Churn: Optional[str] = None

# Example usage
example_input_1 = TelcoCustomerInput(
    customerID="7590-VHVEG",
    gender="Female",
    SeniorCitizen=0,
    Partner="Yes",
    Dependents="No",
    tenure=1,
    PhoneService="No",
    MultipleLines="No phone service",
    InternetService="DSL",
    OnlineSecurity="No",
    OnlineBackup="Yes",
    DeviceProtection="No",
    TechSupport="No",
    StreamingTV="No",
    StreamingMovies="No",
    Contract="Month-to-month",
    PaperlessBilling="Yes",
    PaymentMethod="Electronic check",
    MonthlyCharges=29.85,
    TotalCharges="29.85",
    Churn="Yes"
)
print(example_input_1)

customerID='7590-VHVEG' gender='Female' SeniorCitizen=0 Partner='Yes' Dependents='No' tenure=1 PhoneService='No' MultipleLines='No phone service' InternetService='DSL' OnlineSecurity='No' OnlineBackup='Yes' DeviceProtection='No' TechSupport='No' StreamingTV='No' StreamingMovies='No' Contract='Month-to-month' PaperlessBilling='Yes' PaymentMethod='Electronic check' MonthlyCharges=29.85 TotalCharges='29.85' Churn='Yes'

In [24]:
# Example usage 2: Senior citizen with fiber optic service
example_input_2 = TelcoCustomerInput(
    customerID="7591-ABCDF",
    gender="Male",
    SeniorCitizen=1,
    Partner="No",
    Dependents="No",
    tenure=12,
    PhoneService="Yes",
    MultipleLines="Yes",
    InternetService="Fiber optic",
    OnlineSecurity="Yes",
    OnlineBackup="No",
    DeviceProtection="Yes",
    TechSupport="Yes",
    StreamingTV="Yes",
    StreamingMovies="Yes",
    Contract="One year",
    PaperlessBilling="No",
    PaymentMethod="Credit card",
    MonthlyCharges=89.95,
    TotalCharges="1079.40",
    Churn="No"
)

# Example usage 3: Customer without explicitly setting the optional 'Churn' field
example_input_3 = TelcoCustomerInput(
    customerID="7593-PQRST",
    gender="Male",
    SeniorCitizen=0,
    Partner="No",
    Dependents="No",
    tenure=36,
    PhoneService="Yes",
    MultipleLines="No",
    InternetService="Fiber optic",
    OnlineSecurity="No",
    OnlineBackup="No",
    DeviceProtection="Yes",
    TechSupport="No",
    StreamingTV="Yes",
    StreamingMovies="Yes",
    Contract="Two year",
    PaperlessBilling="No",
    PaymentMethod="Electronic check",
    MonthlyCharges=75.55,
    TotalCharges="2700.00",
    Churn="Yes"
)

# Example usage 4: Long-tenure customer with DSL service
example_input_4 = TelcoCustomerInput(
    customerID="7592-XYZGH",
    gender="Female",
    SeniorCitizen=0,
    Partner="Yes",
    Dependents="Yes",
    tenure=24,
    PhoneService="Yes",
    MultipleLines="No",
    InternetService="DSL",
    OnlineSecurity="No",
    OnlineBackup="Yes",
    DeviceProtection="Yes",
    TechSupport="No",
    StreamingTV="Yes",
    StreamingMovies="No",
    Contract="Two year",
    PaperlessBilling="Yes",
    PaymentMethod="Bank transfer",
    MonthlyCharges=45.30,
    TotalCharges="1092.50",
    Churn="No"
)

In [20]:
from pycaret.classification import load_model, predict_model
import pandas as pd

model = load_model('churn_model')
example_df = pd.DataFrame([example_input_4.dict()])
prediction = predict_model(model, data=example_df)

print(prediction)

Transformation Pipeline and Model Successfully Loaded

   customerID  gender  SeniorCitizen  ... Churn prediction_label  prediction_score
0  7592-XYZGH  Female              0  ...    No               No               0.8

[1 rows x 23 columns]

In [25]:
prediction_1 = predict_model(model, data=pd.DataFrame([example_input_1.dict()]))
prediction_2 = predict_model(model, data=pd.DataFrame([example_input_2.dict()]))
prediction_3 = predict_model(model, data=pd.DataFrame([example_input_3.dict()]))
prediction_4 = predict_model(model, data=pd.DataFrame([example_input_4.dict()]))

print(prediction_1)
print(prediction_2)
print(prediction_3)
print(prediction_4)

   customerID  gender  SeniorCitizen  ... Churn prediction_label  prediction_score
0  7590-VHVEG  Female              0  ...   Yes               No               0.6

[1 rows x 23 columns]
   customerID gender  SeniorCitizen  ... Churn prediction_label  prediction_score
0  7591-ABCDF   Male              1  ...    No              Yes               0.6

[1 rows x 23 columns]
   customerID gender  SeniorCitizen  ... Churn prediction_label  prediction_score
0  7593-PQRST   Male              0  ...   Yes              Yes               0.6

[1 rows x 23 columns]
   customerID  gender  SeniorCitizen  ... Churn prediction_label  prediction_score
0  7592-XYZGH  Female              0  ...    No               No               0.8

[1 rows x 23 columns]